# Generated by Django 4.2.16 on 2024-11-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='course',
        ),
        migrations.AddField(
            model_name='alumni',
            name='campus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='school_program',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='cluster',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='college',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='year_graduated',
            field=models.IntegerField(),
        ),
    ]
